{{- if and .Values.omdb.apiKey (not .Values.omdb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "couchside.omdbSecret" . }}
  labels: {{- include "couchside.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.omdb.existingSecretKey }}: {{ .Values.omdb.apiKey | quote }}
{{- end }}
