#!/usr/bin/env python3
"""Write THIRD_PARTY_NOTICES.txt: the licenses of everything Couchside ships.

    python3 scripts/third-party-notices.py            # rewrite the notices
    python3 scripts/third-party-notices.py --check    # exit 1 if they're stale (CI)

Covers the Go modules compiled into the binary (from `go list -deps`), the npm
packages bundled into the web UI (`npm ls --omit=dev`), and the programs the
container image adds. The same text is written to web/public, so the web UI
embeds it and serves it at /third-party-notices.txt.

Needs Go (GO=/path/to/go to pick one) and web/node_modules installed
(WEB=/path/to/web to use a copy elsewhere, e.g. a scratch build folder).
"""

import glob
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GO = os.environ.get("GO", "go")
WEB = os.environ.get("WEB", os.path.join(ROOT, "web"))
OUTPUTS = [os.path.join(ROOT, "THIRD_PARTY_NOTICES.txt"), os.path.join(ROOT, "web", "public", "third-party-notices.txt")]

LICENSE_GLOBS = ["LICENSE*", "LICENCE*", "COPYING*", "NOTICE*", "PATENTS*"]
RULE = "=" * 78

HEADER = """Couchside third-party notices
=============================

Couchside is released under the MIT License (see LICENSE). It includes the
software below, each under its own license. This file is generated by
scripts/third-party-notices.py.
"""

# Programs the container image adds. They aren't part of Couchside's code:
# Couchside runs them as separate processes.
CONTAINER = """Container image (ghcr.io/timothydodd/couchside)
-----------------------------------------------

The image is based on Alpine Linux and adds these programs. Couchside runs
them as separate processes; it doesn't link them.

- FFmpeg (Alpine package "ffmpeg"): transcoding, probing and recording.
  GPL v2 or later as built by Alpine; see https://ffmpeg.org/legal.html.
  Source: https://ffmpeg.org and the Alpine aports tree,
  https://gitlab.alpinelinux.org/alpine/aports (community/ffmpeg).

- Comskip V0.83 (https://github.com/erikkaashoek/Comskip): commercial
  detection. GPL v2. Built from source, statically linked with argtable2 13
  (LGPL v2, https://argtable.sourceforge.io). The exact source of both is in
  the image at /usr/share/src/comskip-V0.83.tar.gz and
  /usr/share/src/argtable2-13.tar.gz, and in Couchside's Dockerfile.

- Intel Media Driver and libva-intel-driver (x86-64 images only): GPU
  transcoding. MIT. Source: https://github.com/intel/media-driver and
  https://github.com/intel/intel-vaapi-driver.

- Alpine Linux base packages (musl, busybox, ca-certificates, tzdata and the
  libraries FFmpeg uses), each under its own license, recorded in the image's
  package database (`apk info -L`). Source: https://gitlab.alpinelinux.org/alpine/aports.
"""


def run(cmd, cwd):
    return subprocess.run(cmd, cwd=cwd, check=True, capture_output=True, text=True).stdout


def license_texts(folder):
    seen, parts = set(), []
    for pattern in LICENSE_GLOBS:
        for path in sorted(glob.glob(os.path.join(folder, pattern))):
            if path in seen or not os.path.isfile(path):
                continue
            seen.add(path)
            with open(path, encoding="utf-8", errors="replace") as f:
                parts.append(f.read().strip())
    return parts


def section(title, entries):
    out = [title, "-" * len(title), ""]
    for name, version, kind, texts in entries:
        out += [RULE, f"{name} {version}".strip() + (f"  ({kind})" if kind else ""), RULE, ""]
        out += [("\n\n".join(texts) if texts else "(No license file found in the package; see its project page.)"), ""]
    return "\n".join(out)


def go_modules():
    server = os.path.join(ROOT, "server")
    main = run([GO, "list", "-m"], server).strip()
    lines = run([GO, "list", "-deps", "-f", "{{with .Module}}{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}", "./cmd/couchside"], server)
    mods = {}
    for line in lines.splitlines():
        path, version, folder = line.split("\t")
        if path != main:
            mods[path] = (version, folder)
    goroot = run([GO, "env", "GOROOT"], server).strip()
    # No version: CI may build with another Go patch release.
    entries = [("Go standard library", "", "", license_texts(goroot))]
    for path in sorted(mods):
        version, folder = mods[path]
        entries.append((path, version, "", license_texts(folder)))
    return entries


def npm_packages():
    paths = run(["npm", "ls", "--omit=dev", "--all", "--parseable"], WEB).splitlines()
    entries, seen = [], set()
    for line in paths[1:]:  # the first is the web app itself
        # Rebuild the path from node_modules on: npm can mask parts of the prefix.
        folder = os.path.join(WEB, line[line.index("node_modules") :])
        with open(os.path.join(folder, "package.json"), encoding="utf-8") as f:
            pkg = json.load(f)
        key = (pkg["name"], pkg.get("version", ""))
        if key in seen:
            continue
        seen.add(key)
        lic = pkg.get("license")
        entries.append((pkg["name"], pkg.get("version", ""), lic if isinstance(lic, str) else "", license_texts(folder)))
    return sorted(entries)


def build():
    return "\n".join(
        [
            HEADER,
            section("Go modules compiled into the couchside binary", go_modules()),
            section("npm packages bundled into the web UI", npm_packages()),
            CONTAINER,
        ]
    ).rstrip() + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        stale = [p for p in OUTPUTS if not os.path.exists(p) or open(p, encoding="utf-8").read() != text]
        if stale:
            print("Third-party notices are out of date; run python3 scripts/third-party-notices.py:\n  " + "\n  ".join(stale))
            sys.exit(1)
        print("Third-party notices are up to date.")
        return
    for path in OUTPUTS:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    print("Wrote " + ", ".join(os.path.relpath(p, ROOT) for p in OUTPUTS))


if __name__ == "__main__":
    main()
